#!/usr/bin/env php
<?php
define("AUTOLOAD", __DIR__.'/vendor/autoload.php');

use Stafred\Kernel\Console;

$info = [
    "\n>>> [Stafred] Terminal @ " . date ("Y") . "\n\n",
    "\n>>> [Stafred] Terminal (Error: autoload.php not found)\n\n",
    "\n>>> [Stafred] Terminal close\n\n",
];

if (file_exists(AUTOLOAD)) {
    require __DIR__.'/vendor/autoload.php';
    echo $info[0];
} else {
    echo $info[1];
}

Console::run();
echo $info[2];
die;